# Generated by Django 5.1.3 on 2024-12-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
